[colors.primary]
background = "#011418"
foreground = "#839496"

[colors.normal]
black   = "#073642"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#eee8d5"

[colors.bright]
black   = "#4c4c4c"
red     = "#cb4b16"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#93a1a1"
white   = "#fdf6e3"

[font]
size = 12.0

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1.0
