format = """
$username$hostname$directory$character
"""

add_newline = false

[username]
show_always = true
format = '[$user](bold blue)'

[hostname]
ssh_only = false 
format = '[@$hostname](bold blue)'

[directory]
format = ':[$path](bold green)'
truncate_to_repo = false

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](bold red)'
vicmd_symbol = '[V](bold blue)'
